### ISSUE TITLE
Undeclared dependency on Digest::SHA1

### ISSUE THREAD

**Issue by andk** [mamod/DBD-Crate#2]
As per subject. Grep:

http://search.cpan.org/grep?release=DBD-Crate-0.0.2;string=Digest::SHA1;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/72429865

HTH&&Thanks,

**Comment by mamod** [comment]
Thank you for reporting this, this has been fixed with pull request #1 and will be uploaded to CPAN shortly. Strangely, the fix submitted 3 days ago and I didn't get any notification about it !!
